Citizen.CreateThread(function()
	--Brands--
	AddTextEntry('bmw','BMW')
	AddTextEntry('mercedes','Mercedes')
	AddTextEntry('porsche','Porsche')
	AddTextEntry('rolls','Rollys Royce')
	AddTextEntry('dodge','Dodge')
	AddTextEntry('cheverolet','Cheverolet')
	AddTextEntry('vw','Volkswagen')
	AddTextEntry('maserati','Maserati')
	AddTextEntry('ferrari','Ferrari')
	AddTextEntry('honda','Honda')
	AddTextEntry('ford','Ford')
	AddTextEntry('audi','Audi')
	AddTextEntry('lrover','Land Rover')
	AddTextEntry('startech','Startech')
	AddTextEntry('rrover','Range Rover')
	AddTextEntry('bentley','Bentley')
	AddTextEntry('jaguar','Jaguar')
	AddTextEntry('tesla','Tesla')

	--Models--
	AddTextEntry('rrst','Range Rover')
	AddTextEntry('q820','Q8')
	AddTextEntry('bbentayga','Bentayga')
	AddTextEntry('fpacehm','F-Pace SVR')
	AddTextEntry('18x4','X4 Competition')
	AddTextEntry('models','Model S')
	AddTextEntry('rmodmk7','Golf R')
	AddTextEntry('rmodrs6','RS6')
	AddTextEntry('impala67',"67 Impala")
	AddTextEntry('slk55','SLK55 AMG')
	AddTextEntry('g63','G63S AMG')
	AddTextEntry('rmodi8mlb','BMW i8')
	AddTextEntry('rmodgt63','GT63 AMG')
	AddTextEntry('urus2018','Lamborghini Urus')
	AddTextEntry('wraith','Rolls Royce Wraith')
end)