Citizen.CreateThread(function()
	--Brands--
	AddTextEntry('bmw','BMW')
	AddTextEntry('mercedes','Mercedes')
	AddTextEntry('porsche','Porsche')
	AddTextEntry('dodge','Dodge')
	AddTextEntry('cheverolet','Cheverolet')
	AddTextEntry('vw','Volkswagen')
	AddTextEntry('maserati','Maserati')
	AddTextEntry('ferrari','Ferrari')
	AddTextEntry('honda','Honda')
	AddTextEntry('ford','Ford')
	AddTextEntry('audi','Audi')

	--Models--
	AddTextEntry('m2','M2 Competition')
	AddTextEntry('cu2','Accord Mugen')
	AddTextEntry('2014rs5','RS5')
	AddTextEntry('f150','F150 Raptor')
	AddTextEntry('evo9','Evo IX')
	AddTextEntry('718boxster','Boxster S')
	AddTextEntry('tbird','Thunderbird')
	AddTextEntry('16m5','M5 Touring')
	AddTextEntry('mcjcw20','Cooper GP')
	AddTextEntry('boss302','Mustang Boss 302')
end)