Citizen.CreateThread(function()
	--Brands--
	AddTextEntry('bmw','BMW')
	AddTextEntry('mercedes','Mercedes')
	AddTextEntry('porsche','Porsche')
	AddTextEntry('dodge','Dodge')
	AddTextEntry('cheverolet','Cheverolet')
	AddTextEntry('vw','Volkswagen')
	AddTextEntry('maserati','Maserati')
	AddTextEntry('ferrari','Ferrari')
	AddTextEntry('honda','Honda')
	AddTextEntry('ford','Ford')
	AddTextEntry('audi','Audi')
	AddTextEntry('bentley','Bentley')

	--Models--
    AddTextEntry('16challenger','Challenger')
	AddTextEntry('66fastback',"'66 Mustang")
	AddTextEntry('amggtr','AMG GT-R')
	AddTextEntry('demon','Demon')
	AddTextEntry('e63amg','AMG E63')
	AddTextEntry('f82','M4 Competition')
	AddTextEntry('fk8','Civic')
	AddTextEntry('focusrs','Focus RS')
	AddTextEntry('93mustang',"'93 Mustang")
	AddTextEntry('foxmans2','E63 Mansory Edition')
	AddTextEntry('gle63c','AMG GLE63')
	AddTextEntry('granlb','Gran Turismo')
	AddTextEntry('kart','Kart')
	AddTextEntry('levante','Levante')
	AddTextEntry('lw458s','458 Italia')
	AddTextEntry('por959','959')
	AddTextEntry('rmodamgc63','AMG C63')
	AddTextEntry('rmodbmwm8','M8 Competition')
	AddTextEntry('rmodmk7','Golf R')
	AddTextEntry('rs6wb','RS6 Widebody')
	AddTextEntry('rs62','RS6')
	AddTextEntry('sstingray66','Stingray')
	AddTextEntry('brooklands','Brooklands')
	AddTextEntry('bdragon','Continental Dragon-Spec')
end)